const ROUTES={"/":{title:"Inicio",eyebrow:"Panel de herramientas",render:renderDashboard},"/calculator":{title:"Calculadora de precios",eyebrow:"Herramientas",render:renderToolPreview},"/breakeven":{title:"Punto de equilibrio",eyebrow:"Herramientas",render:renderToolPreview},"/whatsapp":{title:"Enlaces de WhatsApp",eyebrow:"Herramientas",render:renderToolPreview},"/qrgenerator":{title:"Generador QR",eyebrow:"Herramientas",render:renderToolPreview},"/invoice":{title:"Cotizaciones y facturas",eyebrow:"Herramientas",render:renderToolPreview},"/copygen":{title:"Generador de copys",eyebrow:"Herramientas",render:renderToolPreview}};
const THEME_KEY="emprendetools-theme";
const $=(id)=>document.getElementById(id);
const el={content:$('page-content'),title:$('page-title'),eyebrow:$('page-eyebrow'),sidebar:$('sidebar'),overlay:$('sidebar-overlay'),menu:$('mobile-menu-button'),close:$('close-sidebar-button'),desktopTheme:$('desktop-theme-button'),mobileTheme:$('mobile-theme-button'),themeLabel:$('theme-label'),toast:$('toast-container')};
function initialTheme(){const t=localStorage.getItem(THEME_KEY);return t==='dark'||t==='light'?t:(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}
function applyTheme(theme){const dark=theme==='dark';document.documentElement.classList.toggle('dark',dark);localStorage.setItem(THEME_KEY,theme);el.themeLabel.textContent=dark?'Modo claro':'Modo oscuro';el.mobileTheme.setAttribute('aria-label',dark?'Cambiar a modo claro':'Cambiar a modo oscuro')}
function toggleTheme(){const dark=document.documentElement.classList.contains('dark');applyTheme(dark?'light':'dark');showToast(dark?'Modo claro activado.':'Modo oscuro activado.')}
function route(){const h=location.hash.replace(/^#/,'');return ROUTES[h]?(h||'/'):'/'}
function navigate(){const r=route(),cfg=ROUTES[r];el.title.textContent=cfg.title;el.eyebrow.textContent=cfg.eyebrow;el.content.replaceChildren(cfg.render(r));document.querySelectorAll('[data-route-link]').forEach(a=>a.classList.toggle('active',(a.dataset.route||'/')===r));closeSidebar();scrollTo({top:0,behavior:'smooth'})}
function openSidebar(){el.sidebar.classList.remove('-translate-x-full');el.overlay.classList.remove('hidden');el.menu.setAttribute('aria-expanded','true');document.body.classList.add('overflow-hidden')}
function closeSidebar(){el.sidebar.classList.add('-translate-x-full');el.overlay.classList.add('hidden');el.menu.setAttribute('aria-expanded','false');document.body.classList.remove('overflow-hidden')}
function card(route,title,description){const a=document.createElement('a');a.href='#'+route;a.dataset.routeLink='';a.dataset.route=route;a.className='app-card group block p-5 sm:p-6';a.innerHTML=`<div class="mb-5 flex items-start justify-between gap-4"><div class="tool-icon"><span class="font-bold">+</span></div><span class="text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-indigo-500">→</span></div><h3 class="mb-2 font-semibold tracking-tight">${title}</h3><p class="text-sm leading-6 text-slate-500 dark:text-slate-400">${description}</p>`;return a}
function renderDashboard(){const w=document.createElement('div');w.innerHTML=`<section class="mb-8 overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-8"><div class="max-w-3xl"><div class="mb-4 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700 dark:border-indigo-900/50 dark:bg-indigo-950/40 dark:text-indigo-300"><span class="h-1.5 w-1.5 rounded-full bg-indigo-500"></span>Tu centro de herramientas</div><h2 class="text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-4xl">Haz crecer tu negocio con herramientas simples.</h2><p class="mt-4 max-w-2xl text-base leading-7 text-slate-500 dark:text-slate-400">Calcula precios, crea enlaces para WhatsApp, genera códigos QR, prepara documentos comerciales y crea textos para vender. Todo directamente desde tu navegador.</p><div class="mt-6"><a href="#/calculator" data-route-link data-route="/calculator" class="primary-button">Empezar ahora →</a></div></div></section><section><div class="mb-5"><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">Herramientas</p><h2 class="mt-1 text-xl font-bold tracking-tight">Todo lo esencial, en un solo lugar</h2></div><div id="tools-grid" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"></div></section>`;const grid=w.querySelector('#tools-grid');[{r:'/calculator',t:'Calculadora de precios',d:'Calcula margen de ganancia y precio de venta.'},{r:'/breakeven',t:'Punto de equilibrio',d:'Descubre cuánto necesitas vender para cubrir tus costos.'},{r:'/whatsapp',t:'Enlaces de WhatsApp',d:'Crea enlaces wa.me con mensajes personalizados.'},{r:'/qrgenerator',t:'Generador QR',d:'Genera códigos QR para tus enlaces y negocio.'},{r:'/invoice',t:'Cotizaciones y facturas',d:'Prepara documentos comerciales listos para PDF.'},{r:'/copygen',t:'Generador de copys',d:'Crea textos comerciales para redes sociales.'}].forEach(x=>grid.appendChild(card(x.r,x.t,x.d)));return w}
function renderToolPreview(r){const w=document.createElement('div');w.innerHTML=`<section class="mx-auto max-w-3xl"><div class="app-card p-6 text-center sm:p-10"><div class="tool-icon mx-auto mb-5">+</div><p class="mb-2 text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">Módulo reservado</p><h2 class="text-2xl font-bold tracking-tight">${ROUTES[r].title}</h2><p class="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-500 dark:text-slate-400">La arquitectura ya está preparada para cargar esta herramienta como módulo independiente en la siguiente fase.</p><div class="mt-7"><a href="#/" data-route-link data-route="/" class="secondary-button">Volver al inicio</a></div></div></section>`;return w}
function showToast(message){const t=document.createElement('div');t.className='toast';t.innerHTML=`<span class="toast-icon">✓</span><p class="pt-0.5 text-sm font-medium leading-5 text-slate-700 dark:text-slate-200">${message}</p>`;el.toast.appendChild(t);setTimeout(()=>{t.classList.add('toast-out');setTimeout(()=>t.remove(),180)},2500)}
function registerSW(){if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
el.menu.addEventListener('click',openSidebar);el.close.addEventListener('click',closeSidebar);el.overlay.addEventListener('click',closeSidebar);el.desktopTheme.addEventListener('click',toggleTheme);el.mobileTheme.addEventListener('click',toggleTheme);addEventListener('hashchange',navigate);addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar()});applyTheme(initialTheme());registerSW();navigate();